// Complete mapping of database tables to TanStack query key prefixes
export const TABLE_QUERY_KEY_MAP: Record<string, string[][]> = {
  students: [
    ["students"],
    ["students-idcard"],
    ["students-attendance"],
    ["students-marks"],
    ["students-manual"],
    ["exam-students"],
    ["promotion-students"],
    ["all-students-lookup"],
    ["recent-students"],
    ["dash-students"],
    ["report-students"],
    ["collect-students"],
    ["ledger-students"],
    ["unlinked-students-for-link"],
    ["teacher-student-count"],
    ["student-self"],
    ["student-self-pay"],
    ["student-school"],
  ],
  classes: [
    ["classes"],
    ["classes-idcard"],
    ["exam-classes"],
    ["accounts-classes"],
    ["collect-classes"],
    ["report-classes"],
    ["teacher-assigned-classes"],
    ["promotion-students"],
  ],
  sections: [
    ["sections"],
    ["all-sections"],
    ["all-sections-form"],
    ["exam-sections"],
    ["accounts-sections"],
  ],
  teachers: [
    ["teachers"],
    ["teachers-idcard"],
    ["dash-teachers"],
    ["report-teachers"],
    ["salary-teachers"],
    ["teacher-self"],
    ["teacher-school"],
    ["teacher-hw-profile"],
  ],
  teacher_assignments: [
    ["teacher-assignments"],
    ["teacher-assigned-classes"],
    ["classes"],
    ["attendance-scope"],
    ["teacher-student-count"],
  ],
  staff: [
    ["staff"],
    ["staff-idcard"],
    ["dash-staff"],
    ["report-staff"],
    ["salary-staff"],
  ],
  attendance: [
    ["attendance-records"],
    ["existing-attendance"],
    ["attendance-chart"],
    ["monthly-attendance"],
    ["dash-attendance"],
    ["report-attendance"],
    ["student-attendance"],
    ["student-attendance-all"],
    ["student-attendance-stats"],
    ["user-attendance"],
  ],
  teacher_attendance: [
    ["teacher-attendance-today"],
    ["attendance-records"],
    ["existing-attendance"],
    ["report-attendance"],
  ],
  staff_attendance: [
    ["attendance-records"],
    ["existing-attendance"],
    ["report-attendance"],
  ],
  subject_setups: [
    ["subject-setups"],
    ["final-subject-setups"],
    ["student-subject-setups"],
    ["all-subjects-lookup"],
  ],
  subjects: [
    ["subjects"],
    ["subject-setups"],
    ["all-subjects-lookup"],
  ],
  homework: [
    ["homework"],
    ["teacher-homework-list"],
    ["student-homework"],
    ["student-homework-list"],
  ],
  homework_submissions: [
    ["homework"],
    ["student-homework"],
    ["student-homework-list"],
  ],
  notices: [
    ["notices"],
    ["recent-notices"],
    ["student-notices"],
  ],
  marks: [
    ["marks"],
    ["marks-ledger"],
    ["existing-marks"],
    ["final-result-marks"],
    ["student-marks"],
    ["student-final-marks"],
    ["report-grades"],
  ],
  results: [
    ["results"],
    ["student-exams"],
    ["student-latest-results"],
    ["report-grades"],
  ],
  final_results: [
    ["final-results"],
    ["student-final-results"],
    ["report-grades"],
  ],
  fees: [
    ["student-fees"],
    ["dash-fees-detailed"],
  ],
  fee_categories: [
    ["fee-categories"],
    ["fee-structures"],
    ["income-categories"],
  ],
  fee_structures: [
    ["fee-structures"],
  ],
  student_ledger: [
    ["student-ledger"],
    ["student-ledger-self"],
    ["student-ledger-school"],
    ["collect-ledger"],
    ["admit-student-ledgers"],
    ["accounts-dashboard"],
    ["report-payments"],
    ["dash-fees-detailed"],
  ],
  payments: [
    ["student-my-payments"],
    ["student-payment-status"],
    ["student-payments"],
    ["dash-fees-detailed"],
    ["report-payments"],
  ],
  receipts: [
    ["receipts"],
    ["recent-receipts"],
    ["student-receipts-self"],
    ["accounts-dashboard"],
    ["report-payments"],
  ],
  financial_accounts: [
    ["financial-accounts"],
    ["accounts-dashboard"],
    ["account-txns"],
  ],
  income_transactions: [
    ["income-txns"],
    ["accounts-dashboard"],
    ["account-txns"],
    ["dash-fees-detailed"],
  ],
  expense_transactions: [
    ["expense-txns"],
    ["accounts-dashboard"],
    ["account-txns"],
  ],
  income_categories: [
    ["income-categories"],
  ],
  expense_categories: [
    ["expense-categories"],
  ],
  salary_payments: [
    ["salary-payments"],
    ["accounts-dashboard"],
  ],
  accounts_settings: [
    ["accounts-settings"],
  ],
  payment_gateway_settings: [
    ["payment-gateways"],
  ],
  schools: [
    ["schools"],
    ["schools-list"],
    ["schools-deleted"],
    ["school"],
    ["school-info"],
    ["school-details"],
    ["school-stats"],
    ["school-report"],
    ["school-settings"],
    ["report-schools-list"],
    ["report-platform-stats"],
    ["dash-schools-count"],
    ["dash-schools-list"],
    ["dash-active-schools"],
    ["dash-suspended-schools"],
    ["sidebar-school-info"],
    ["topbar-school-info"],
    ["school-details-idcard"],
    ["exam-school"],
  ],
  platform_settings: [
    ["platform-settings-global"],
    ["platform-stats"],
    ["report-platform-stats"],
  ],
  profiles: [
    ["selected-user-details"],
    ["teacher-self"],
    ["student-self"],
    ["teacher-hw-profile"],
  ],
  agreements: [
    ["owner-signature"],
  ],
  user_roles: [
    ["user-roles"],
    ["selected-user-details"],
  ],
};

export const CORE_MONITORED_TABLES = Object.keys(TABLE_QUERY_KEY_MAP);
